version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout
      - run:
          name: get deps
          command: |
            go get -u -v github.com/golang/dep/cmd/dep
            dep ensure
      - run:
          name: build
          command: |
            make build
            make build.cli
